// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/forum': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/forum').default>>>>
    }
    '/api/legislators': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/legislators').default>>>>
    }
    '/api/news': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/news').default>>>>
    }
    '/api/petitions': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/petitions').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
  }
}
export {}