// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/21/2025, 8:08:53 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/carltanner/dev/igotrights_nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carltanner/dev/igotrights_nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carltanner/dev/igotrights_nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carltanner/dev/igotrights_nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/carltanner/dev/igotrights_nuxt/plugins/**/*.{js,ts,mjs}","/Users/carltanner/dev/igotrights_nuxt/composables/**/*.{js,ts,mjs}","/Users/carltanner/dev/igotrights_nuxt/utils/**/*.{js,ts,mjs}","/Users/carltanner/dev/igotrights_nuxt/pages/news.vue","/Users/carltanner/dev/igotrights_nuxt/pages/news.vue","/Users/carltanner/dev/igotrights_nuxt/pages/news.vue","/Users/carltanner/dev/igotrights_nuxt/pages/about.vue","/Users/carltanner/dev/igotrights_nuxt/pages/about.vue","/Users/carltanner/dev/igotrights_nuxt/pages/about.vue","/Users/carltanner/dev/igotrights_nuxt/pages/index.vue","/Users/carltanner/dev/igotrights_nuxt/pages/index.vue","/Users/carltanner/dev/igotrights_nuxt/pages/index.vue","/Users/carltanner/dev/igotrights_nuxt/pages/actions.vue","/Users/carltanner/dev/igotrights_nuxt/pages/actions.vue","/Users/carltanner/dev/igotrights_nuxt/pages/actions.vue","/Users/carltanner/dev/igotrights_nuxt/pages/privacy.vue","/Users/carltanner/dev/igotrights_nuxt/pages/privacy.vue","/Users/carltanner/dev/igotrights_nuxt/pages/privacy.vue","/Users/carltanner/dev/igotrights_nuxt/pages/[...slug].vue","/Users/carltanner/dev/igotrights_nuxt/pages/[...slug].vue","/Users/carltanner/dev/igotrights_nuxt/pages/[...slug].vue","/Users/carltanner/dev/igotrights_nuxt/pages/community.vue","/Users/carltanner/dev/igotrights_nuxt/pages/community.vue","/Users/carltanner/dev/igotrights_nuxt/pages/community.vue","/Users/carltanner/dev/igotrights_nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/carltanner/dev/igotrights_nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/carltanner/dev/igotrights_nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;